---
- hosts: localhost
  connection: local
  any_errors_fatal: true
  vars_files:
    - group_vars/common.yaml
  roles:
    - role: VivaReal.aws-lc
    - role: VivaReal.aws-elb
    - role: VivaReal.aws-asg
    - { role: VivaReal.aws-route53, aws_route53_value: "{{ aws_elb_dns_name }}" }
    - role: VivaReal.slack-notify